### PR TITLE
Add Drush/Console command to download packages.

### PR DESCRIPTION
**Pull request by mglaman**
hyper

Commands:

```sh
../bin/drupal ludwig:download
```

or

```sh
../bin/drush ludwig-download
```

For Drush I hooked into post_pm_download to automatically invoke a subprocess and download packages.

### CODE REVIEW

**Comment by mglaman** [comment]
packages___site-install

**Comment by mglaman** [comment]
hyper

**Comment by mglaman** [comment]
hyper

**Comment by bojanz** [comment]
Nice and clean. Tweaked the messages, opened a few followups. Thanks!

Commit in 93b0e2d4a539555dd25e5448291343fb7fbf1be0.

**Pull request closed without merging**
